name: ci-native

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/ci-quarkus-native.yml"
      - "validity/**"
      - "docker-compose.yaml"
  pull_request:
    branches: [main]

permissions:
  packages: write

concurrency:
  group: ci-native

jobs:
  build-native:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: login ghcr.io
        uses: docker/login-action@v1.8.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: true
      - name: checkout
        uses: actions/checkout@v2
      - name: gradle build push native
        run: ./gradlew build -Dquarkus.package.type=native -Dquarkus.native.container-build=true -Dquarkus.container-image.push=true -Dquarkus.container-image.image=ghcr.io/LesDomen/ia-validity.native:latest '-Dquarkus.jib.labels."org.opencontainers.image.revision"='$GITHUB_SHA
