name: ci-native

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/ci-spring.yml"
      - "purchase/**"
  pull_request:
    branches: [main]

permissions:
  packages: write

concurrency:
  group: ci-native

jobs:
  build-native:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"
      - name: login ghcr.io
        uses: docker/login-action@v1.8.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: true
      - name: checkout
        uses: actions/checkout@v2
      - name: gradle build push
        run: cd purchase && ./mvnw spring-boot:build-image -Dspring-boot.build-image.imageName=ghcr.io/LesDomen/ia-purchase:latest
      - name: docker push
      - run: docker image push ghcr.io/LesDomen/ia-purchase:latest
